env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  max-len: 
    - 2
    - code: 120
  new-parens: 2
settings:
  react:
    createClass: createReactClass
    pragma: React
    version: detect